src/Entity/Lignec.php
<?php

namespace App\Entity;
use App\Entity\Panier;
use App\Repository\LignecRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass=LignecRepository::class)
 */
class Lignec
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

   /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $idP;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @var \Panier
     * @ORM\ManyToOne(targetEntity=Panier::class, inversedBy="lignes")
     *  @JoinColumn(name="id_panier", referencedColumnName="id_panier")
     * 
     */
    private $id_panier;

    public function getId(): ?int
    {
        return $this->id;
    }

 
    public function __construct()
    {
        
        $this->quantite = 0;
    }
    public function getIdP(): ?int
    {
        return $this->idP;
    }

    public function setIdP(int $idP): self
    {
        $this->idP = $idP;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }
    public function ajouterQuantite(int $qte)
	{
		$this->quantite += qte;
        return $this;
	}
    	public function dimQuantite(int $qte)
	{
		$this->quantite -= qte;
	}
    public function setPrixLigne(): void
	{
              // Produit $p=new Produit();
  
        $this->prix= 200 /*$p->getbyid($this.idP)*/ * $this->getQuantite();
		
	}
    public function getPrix(): ?float
	{
              // Produit $p=new Produit();
  
        return $this->prix;
		
	}
        public function prixbypanier(String $idpanier) :?float
        {  $price;
            if($this->id_panier==$idpanier)
            {
              return $price=$this->getPrixLigne();
            }
            return 0;
        }

        public function getIdPanier(): ?Panier
        {
            return $this->id_panier;
        }

        public function setIdPanier(?Panier $panier): self
        {
            $this->id_panier = $panier;

            return $this;
        }








}

src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PanierRepository::class)
 */
class Panier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id_panier;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $id_client;

    /**
     * @ORM\Column(type="float")
     */
    private $totalpanier;

    /**
     * @ORM\OneToMany(targetEntity=Lignec::class, mappedBy="id_panier")
     *cascade={"remove"} 
     *
     */
    private $lignes;

    public function __construct()
    {
        $this->lignes = new ArrayCollection();
    }
    public function __toString(): string
{
    return $this->id_panier;  // or some string field in your Vegetal Entity 
}

    public function getId_panier(): ?int
    {
        return $this->id_panier;
    }

    public function getIdClient(): ?int
    {
        return $this->id_client;
    }

    public function setIdClient(int $id_client): self
    {
        $this->id_client = $id_client;

        return $this;
    }

    public function getTotalpanier(): ?float
    {
        return $this->totalpanier;
    }

    public function setTotalpanier(float $totalpanier): self
    {
        $this->totalpanier = $totalpanier;

        return $this;
    }
    public function calculerPanier() :float {
       $total = 0;
       foreach($lignes->getIterator() as $i => $item) {

            $total += $item->prixbypanier($this->getId_panier());
        }
        return $total;
    }

    /**
     * @return Collection<int, Lignec>
     */
    public function getLignes(): Collection
    {
        return $this->lignes;
    }

    public function addLigne(Lignec $ligne): self
    {
        if (!$this->lignes->contains($ligne)) {
            $this->lignes[] = $ligne;
            $ligne->setPanier($this);
        }

        return $this;
    }

    public function removeLigne(Lignec $ligne): self
    {
        if ($this->lignes->removeElement($ligne)) {
            // set the owning side to null (unless already changed)
            if ($ligne->getPanier() === $this) {
                $ligne->setPanier(null);
            }
        }

        return $this;
    }
}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Controller\LignecController;
use App\Form\PanierType;
use App\Repository\PanierRepository;
use App\Repository\LignecRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/panier")
 */
class PanierController extends AbstractController
{
    /**
     * @Route("/", name="app_panier_index", methods={"GET"})
     */
    public function index(PanierRepository $panierRepository): Response
    {
        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_panier_new", methods={"GET", "POST"})
     */

    public function new(Request $request,int $idclient,string $id_panier,PanierRepository $panierRepository,LignecRepository $repo) : void
    {
    $panier = new Panier();
    $total=$this->calculerPanier($panier->getId_panier(),$repo,$request);
$panier->setIdClient($idclient);
$panier->setTotalpanier($total);
$panierRepository->add($panier);
        echo 'Envoyé';
}

public function calcultotal(string $idpanier,LignecRepository $repo,Request $req) :float
{ 
   $ligne=new LignecController();
$total =0;
    
            $total+=$ligne->prix( $repo,$req,$idpanier);
         return $total;  
}
    /**
     * @Route("/{id_panier}", name="app_panier_show", methods={"GET"})
     */
    public function show(Panier $panier): Response
    {
        return $this->render('panier/show.html.twig', [
            'panier' => $panier,
        ]);
    }

    /**
     * @Route("/{id_panier}/edit", name="app_panier_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Panier $panier, PanierRepository $panierRepository): Response
    {
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $panierRepository->add($panier);
            return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_panier}", name="app_panier_delete", methods={"POST"})
     */
    public function delete(Request $request, Panier $panier, PanierRepository $panierRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId_panier(), $request->request->get('_token'))) {
            $panierRepository->remove($panier);
        }

        return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
    }
    public function chercherpanierbyuser(PanierRepository $repo,Request $req,int $idclient)
    {
    
    
        $panier=$repo->findOneBy(['id_client'=>$idclient]); 
        return $panier;
        }
        public function miseajour(string $idpanier,LignecRepository $repo,Request $req,PanierRepository $rep,int $idclient): void
        {

            $total=$this->calcultotal($idpanier,$repo,$req);
            $panier=new Panier();
            $panier=$rep->findOneByiduser($idclient);
            $panier->setTotalpanier($total);
            $rep->add($panier);
        }
        public function vider(Request $request,int $id_client,PanierRepository $panierRepository)
        {

           $panierRepository->vider($id_client);
        }
}

templates/panier/_delete_form.html.twig
<form method="post" action="{{ path('app_panier_delete', {'id_panier': panier.id_panier}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id_panier) }}">
    <button class="btn">Delete</button>
</form>

templates/panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Panier{% endblock %}

{% block body %}
    <h1>Edit Panier</h1>

    {{ include('panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_panier_index') }}">back to list</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
<div class="row" style="display: flex;align-items: rightcenter;justify-content: rightcenter;margin-top: 150px;">

    <div class="col-lg-4">

        <div class="card">
            <div class="card-body">
    <h1>Votre panier</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Total panier</th>
           
            </tr>
        </thead>
        <tbody>
        {% for panier in paniers %}
            <tr>
        
                <td>{{ panier.totalpanier }}</td>
         
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_panier_new') }}">Passez à la commande</a>
       </div>
        </div>

    </div>



</div>
{% endblock %}

templates/panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Panier{% endblock %}

{% block body %}
<div class="container">
<div id="content-wrapper">
<section id="main">
<div class="cart-grid row">

<div class="cart-grid-body col-xs-12 col-lg-8">

<div class="card cart-container">
<div class="card-block">
<h1 class="h1">Panier</h1>
</div>
<div class="cart-overview js-cart" data-refresh-url="//pharma-shop.tn/panier?ajax=1&action=refresh">
<span class="no-items">Il n'y a plus d'articles dans votre panier</span>
</div>
</div>
<a class="label" href="https://pharma-shop.tn/">
<i class="material-icons">chevron_left</i>Continuer mes achats
</a>

<div id="loylalty_cart_parent"> <div id="loyalty_cart">
<div class="icons-cadeaux"></div>
<div> Ajoutez des produits à votre panier pour gagnier des points de fidélité.</div>
</div>
</div>
</div>

<div class="cart-grid-right col-xs-12 col-lg-4">
<h2 class="titlecart">Votre panier</h2>
<div class="card cart-summary">
<div class="cart-detailed-totals">
<div class="card-block">
<div class="cart-summary-line" id="cart-subtotal-products">
<span class="label js-subtotal">
0 articles
</span>
<span class="value">
0,000 TND
</span>
</div>
</div>
<div class="card-block cart-summary-totals">
<div class="cart-summary-line cart-total">
<span class="label">Total&nbsp;TTC</span>
<span class="value">0,000 TND</span>
</div>
</div>
</div>
<div class="checkout text-sm-center card-block">
<button type="button" class="btn btn-primary disabled" disabled>Commander</button>
</div>
</div>
</div>
</div>
</section>
</div>
</div>
</section>
    <h1>Create new Panier</h1>

    {{ include('panier/_form.html.twig') }}

    <a href="{{ path('app_panier_index') }}">back to list</a>
{% endblock %}

templates/panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_panier</th>
                <td>{{ panier.idPanier }}</td>
            </tr>
            <tr>
                <th>Id_client</th>
                <td>{{ panier.idClient }}</td>
            </tr>
            <tr>
                <th>Totalpanier</th>
                <td>{{ panier.totalpanier }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_panier_index') }}">back to list</a>

    <a href="{{ path('app_panier_edit', {'id_panier': panier.id_panier}) }}">edit</a>

    {{ include('panier/_delete_form.html.twig') }}
  
{% endblock %}